### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by chasebank** [TheMushrr00m/cordovue#5]
Any idea why that error is showing in iOS 9 and 8? I've been trying to figure it out for hours and can't fix it. 

My app has been rendering a blank page with that console error, and I just unzipped a fresh download of this repo, with no changes, and see the same thing.

The full error:
```
VMundefined build.js:31337 SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
    (anonymous function) @ VMundefined build.js:31337
```

Typescript stuff keeps popping up in my searches, which is weird...

Edit: NVM... I'm also getting this with the webpack-simple template... will update this post with a fix when I find it, for future victims.

**Comment by chasebank** [comment]
Appears to be related to some [webpack issue](https://github.com/webpack/webpack-dev-server/issues/1101), and has been noted on the [webpack-simple template](https://github.com/vuejs-templates/webpack-simple/issues/148).

Downgrading webpack-dev-server works as a fix

```
npm uninstall webpack-dev-server
npm install -D webpack-dev-server@2.7.1
```

**Comment by TheMushrr00m** [comment]
I can't check this behavior but i'm glad to read about your "fix".
I hope that webpack's team fix this soon, btw, i'm going to try to replicate this to discard any issue about this repo.
